source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FirebaseRxSwiftExtensions_Example' do
  pod "FirebaseRxSwiftExtensions", :path => "../"
end

target 'FirebaseRxSwiftExtensions_Tests' do
  pod "FirebaseRxSwiftExtensions", :path => "../"
end
