source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FirebaseRxSwiftExtensions_Example', :exclusive => true do
  pod "FirebaseRxSwiftExtensions", :path => "../"
end

target 'FirebaseRxSwiftExtensions_Tests', :exclusive => true do
  pod "FirebaseRxSwiftExtensions", :path => "../"
end
